name: scroll_overlay
description: A Flutter app that overlays a native scroll view over the Flutter view.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
