name: scroll_overlay
description: A Flutter app that overlays a native scroll view over the Flutter view.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
